const puzzlesTextPlus = [
  {
    text: 'принимаешь и любишь себя',
    xm: '26px',
    ym: '45px',
    xt: '55px',
    yt: '87px',
    maxWidth: '109px',
    maxWidthTab: '160px',
  },
  {
    text: 'создаешь жизнь своей мечты',
    xm: '188px',
    ym: '40px',
    xt: '292px',
    yt: '82px',
    maxWidth: '90px',
    maxWidthTab: '138px',
  },
  {
    text: 'живешь в потоке и видишь знаки',
    xm: '21px',
    ym: '190px',
    xt: '22px',
    yt: '317px',
    maxWidth: '106px',
    maxWidthTab: '160px',
  },
  {
    text: 'раскрываешь и реализовываешь свои таланты',
    xm: '170px',
    ym: '195px',
    xt: '510px',
    yt: '80px',
    maxWidth: '115px',
    maxWidthTab: '160px',
  },
  {
    text: 'следуешь истинному предназначению',
    xm: '10px',
    ym: '348px',
    xt: '522px',
    yt: '310px',
    maxWidth: '137px',
    maxWidthTab: '160px',
  },
  {
    text: 'выстраиваешь гаромничные отношения',
    xm: '188px',
    ym: '346px',
    xt: '288px',
    yt: '541px',
    maxWidth: '83px',
    maxWidthTab: '160px',
  },

  {
    text: 'живешь в щедрости, богатстве и изобилии',
    xm: '18px',
    ym: '490px',
    xt: '72px',
    yt: '541px',
    maxWidth: '115px',
    maxWidthTab: '160px',
  },
  {
    text: 'вносишь вклад в счастливое будущее нашего мира',
    xm: '184px',
    ym: '490px',
    xt: '517px',
    yt: '541px',
    maxWidth: '115px',
    maxWidthTab: '160px',
  },
  {
    text: 'трансформируешь жизненные ценности',
    xm: '184px',
    ym: '490px',
    xt: '277px',
    yt: '306px',
    maxWidth: '115px',
    maxWidthTab: '160px',
  },
];

export default puzzlesTextPlus;
