const puzzlesText = [
  {
    text: 'не умеешь отказывать другим',
    xm: '26px',
    ym: '30px',
    xt: '262px',
    yt: '128px',
    maxWidth: '109px',
    maxWidthTab: '160px',
  },
  {
    text: 'не понимаешь свое предназначение',
    xm: '180px',
    ym: '40px',
    xt: '480px',
    yt: '600px',
    rt: '-6deg',
    maxWidth: '104px',
    maxWidthTab: '185px',
  },
  {
    text: `не можешь раскрыть свой потенциал`,
    xm: '17px',
    ym: '180px',
    xt: '258px',
    yt: '340px',
    maxWidth: '106px',
    maxWidthTab: '160px',
  },
  {
    text: 'не принимаешь, не ценишь себя',
    xm: '170px',
    ym: '195px',
    xt: '35px',
    yt: '147px',
    maxWidth: '118px',
    maxWidthTab: '160px',
  },
  {
    text: 'постоянно попадаешь в неприятные ситуации',
    xm: '10px',
    ym: '365px',
    r: '-6deg',
    xt: '44px',
    yt: '328px',
    maxWidth: '137px',
    maxWidthTab: '160px',
  },
  {
    text: 'постоянно находишься в состоянии тревожности',
    xm: '183px',
    ym: '316px',
    xt: '504px',
    yt: '124px',
    rt: '18deg',
    maxWidth: '83px',
    maxWidthTab: '160px',
  },

  {
    text: 'не знаешь куда двигаться и чем заниматься',
    xm: '184px',
    ym: '509px',
    xt: '520px',
    yt: '367px',
    r: '-3deg',
    maxWidth: '109px',
    maxWidthTab: '160px',
  },
  {
    text: 'не можешь найти общий язык с близкими людьми',
    xm: '184px',
    ym: '509px',
    xt: '270px',
    yt: '530px',
    r: '-3deg',
    maxWidth: '109px',
    maxWidthTab: '112px',
  },

];

export default puzzlesText;
